no lock

diff --git a/pi-install-runner b/pi-install-runner
--- a/pi-install-runner
+++ b/pi-install-runner
@@ -6,13 +6,13 @@ fi
 repo=$1
 target=$2
 log_dir=$3
-
 date_str=$(date +%Y-%m-%d:%H:%M:%S)
 log_file="$log_dir/run_$date_str.log"
 echo "--- run install $date_str ---"
 echo "Repo: $repo "
 echo "target: $target"
 echo "log_file: $log_file"
+
 mkdir -p $log_dir
 has_changes=false
 if [ ! -e $target ]; then
@@ -38,7 +38,7 @@ if [ "$has_changes" = true ] ;then
   if  [ $? -eq 0 ] ; then
     echo "update successful."
   else
-    echo "update ends with errors: see $log_file" 
+    >&2 echo "update ends with errors: see $log_file" 
   fi
 fi
 echo "install finished. had changes: $has_changes "
