fix runner

diff --git a/pi-install-runner b/pi-install-runner
--- a/pi-install-runner
+++ b/pi-install-runner
@@ -4,41 +4,46 @@ if [ $# != 3 ]; then
     exit 0
 fi
 repo=$1
-target=$2
-log_dir=$3
-date_str=$(date +%Y-%m-%d:%H:%M:%S)
-log_file="$log_dir/run_$date_str.log"
+target="$2"
+checkout="$target/checkout"
+date_str=$(date +%Y-%m-%d-%H%M%S)
 echo "--- run install $date_str ---"
 echo "Repo: $repo "
-echo "target: $target"
-echo "log_file: $log_file"
+echo "checkout: $checkout"
 
-mkdir -p $log_dir
-has_changes=false
-if [ ! -e $target ]; then
-  echo "no target found. Clone $repo to target"
-  git clone "$repo" "$target"
-  has_changes=true
-  cd $target
+need_update=false
+mkdir -p "$target"
+if [ -e "$target/current_run" ]; then
+ echo "last update was not successful."
+ need_update=true
+fi
+touch "$target/current_run"
+if [ ! -e "$checkout" ]; then
+  echo "no target found. Clone $repo to $checkout"
+  git clone "$repo" "$checkout"
+  need_update=true
+  cd $checkout
   echo "repo checkout for the first time."
 else
-  cd $target
+  cd $checkout
   hash=$(git rev-parse HEAD)
   git pull
   new_hash=$(git rev-parse HEAD)
   if [ "$hash" != "$new_hash" ]; then
     echo "repo has been changed."
-    has_changes=true
-  fi  
-fi
-
-if [ "$has_changes" = true ] ;then
-  echo "run update:"
-  bash ./update.sh > "$log_file"  2>&1
-  if  [ $? -eq 0 ] ; then
-    echo "update successful."
-  else
-    >&2 echo "update ends with errors: see $log_file" 
+    need_update=true
   fi
 fi
-echo "install finished. had changes: $has_changes "
+
+if [ "$need_update" = true ] ;then
+  echo "--- run update ..."
+  bash ./update.sh   2>&1
+  if  [ $? -eq 0 ] ; then
+    rm "$target/current_run"
+    echo "update successful."
+  else
+    >&2 echo "update ends with errors: see $log_file"
+  fi
+fi
+echo "install finished. need_update: $need_update "
+
